title: AI Conference Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: IIIT talks
author: Abhishek Jha

domain: "aideadlin.es"
baseurl: ""

twitter_username: abhishekjha2010
twitter_hashtag: machinelearning
github_username: abskjha
github_repo: iiit_talks

markdown: kramdown
ga_id: XXXX
