title: Talks@IIIT-Hyderabad # (Maintained by @abskjha)
# email: abhshkdz@vt.edu
description: IIIT talks
author: Abhishek Jha

domain: "abskjha.github.io/iiit_talks"
baseurl: "https://abskjha.github.io/iiit_talks"

twitter_username: abhishekjha2010
twitter_hashtag: machinelearning
github_username: abskjha
github_repo: iiit_talks

markdown: kramdown
# ga_id: XXXX
